--- Tables Creation
CREATE TABLE countries(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name varchar(255), currency_code varchar(10), phone_code varchar(10))

CREATE TABLE occupations (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type varchar(20))

CREATE TABLE visits (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type varchar(20))

CREATE TABLE patients (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, file_number varchar(255), first_name varchar(255), last_name varchar(255), full_name varchar(255), gender varchar(10), country_id integer, civil_id_number varchar(12), first_phone_number varchar(25), second_phone_number varchar(25), email varchar(255), created_at datetime, updated_at datetime, FOREIGN KEY (country_id) REFERENCES countries)

CREATE TABLE employees (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, first_name varchar(255), last_name varchar(255), full_name varchar(255) ,gender varchar(10), occupation_id integer, country_id integer, civil_id_number varchar(12), first_phone_number varchar(25), second_phone_number varchar(25), email varchar(255), created_at datetime, updated_at datetime, FOREIGN KEY (occupation_id) REFERENCES occupations FOREIGN KEY (country_id) REFERENCES countries)

CREATE TABLE appointments (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, start datatetime, end datetime, patient_id integer, employee_id integer, visit_id integer, FOREIGN KEY (patient_id) REFERENCES patients, FOREIGN KEY (employee_id) REFERENCES employees, FOREIGN KEY (visit_id) REFERENCES visits)

CREATE TABLE invoices (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, patient_id integer, date datetime, price decimal, visit_id integer, FOREIGN KEY (patient_id) REFERENCES patients, FOREIGN KEY (visit_id) REFERENCES visits)

CREATE TABLE roles (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, type varchar(255));

CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, username varchar(255), email varchar(255), hashed_password varchar(255), salt varchar(255), role_id integer, FOREIGN KEY (role_id) REFERENCES roles);

--- Roles
INSERT INTO roles VALUES (1, "Administrator")
INSERT INTO roles VALUES (2, "Operator")
INSERT INTO roles VALUES (3, "Viewer")
--- Occupation 
INSERT INTO occupations VALUES (1, "Physician")
INSERT INTO occupations VALUES (2, "Secretary")
INSERT INTO occupations VALUES (3, "Therapist")
--- Visits
INSERT INTO visits VALUES (1, "Assessment")
INSERT INTO visits VALUES (2, "Home Visit")
INSERT INTO visits VALUES (3, "Medical Tools")
INSERT INTO visits VALUES (4, "Massage")
INSERT INTO visits VALUES (5, "Treatment")
--- Countries
INSERT INTO countries VALUES (1, "Afghanistan", "AFN", "+93")
INSERT INTO countries VALUES (2, "Albania", "ALL", "+355")
INSERT INTO countries VALUES (3, "Algeria", "DZD", "+213")
INSERT INTO countries VALUES (4, "Andorra", "EUR", "+376")
INSERT INTO countries VALUES (5, "Angola", "AOA", "+244")
INSERT INTO countries VALUES (6, "Argentina", "ARS", "+54")
INSERT INTO countries VALUES (7, "Armenia", "AMD", "+374")
INSERT INTO countries VALUES (8, "Australia", "AUD", "+61")
INSERT INTO countries VALUES (9, "Austria", "EUR", "+43")
INSERT INTO countries VALUES (10, "Azerbaijan", "AZN", "+994")
INSERT INTO countries VALUES (11, "Bahamas", "BSD", "+1-242")
INSERT INTO countries VALUES (12, "Bahrain", "BHD", "+973")
INSERT INTO countries VALUES (13, "Bangladesh", "BDT", "+880")
INSERT INTO countries VALUES (14, "Barbados", "BBD", "+1-246")
INSERT INTO countries VALUES (15, "Belarus", "BYR", "+375")
INSERT INTO countries VALUES (16, "Belgium", "EUR", "+32")
INSERT INTO countries VALUES (17, "Belize", "BZD", "+501")
INSERT INTO countries VALUES (18, "Benin", "XOF", "+229")
INSERT INTO countries VALUES (19, "Bhutan", "BTN", "+975")
INSERT INTO countries VALUES (20, "Bolivia", "BOB", "+591")
INSERT INTO countries VALUES (21, "Bosnia and Herzegovina", "BAM", "+387")
INSERT INTO countries VALUES (22, "Botswana", "BWP", "+267")
INSERT INTO countries VALUES (23, "Brazil", "BRL", "+55")
INSERT INTO countries VALUES (24, "Brunei", "BND", "+673")
INSERT INTO countries VALUES (25, "Bulgaria", "BGN", "+359")
INSERT INTO countries VALUES (26, "Burkina Faso", "XOF", "+226")
INSERT INTO countries VALUES (27, "Burundi", "BIF", "+257")
INSERT INTO countries VALUES (28, "Cambodia", "KHR", "+855")
INSERT INTO countries VALUES (29, "Cameroon", "XAF", "+237")
INSERT INTO countries VALUES (30, "Canada", "CAD", "+1")
INSERT INTO countries VALUES (31, "Cape Verde", "CVE", "+238")
INSERT INTO countries VALUES (32, "Central African Republic", "XAF", "+236")
INSERT INTO countries VALUES (33, "Chad", "XAF", "+235")
INSERT INTO countries VALUES (34, "Chile", "CLP", "+56")
INSERT INTO countries VALUES (35, "China", "CNY", "+86")
INSERT INTO countries VALUES (36, "Colombia", "COP", "+57")
INSERT INTO countries VALUES (37, "Comoros", "KMF", "+269")
INSERT INTO countries VALUES (38, "Congo", "CDF", "+243")
INSERT INTO countries VALUES (39, "Costa Rica", "CRC", "+506")
INSERT INTO countries VALUES (40, "Cote d'Ivoire", "XOF", "+225")
INSERT INTO countries VALUES (41, "Croatia", "HRK", "+385")
INSERT INTO countries VALUES (42, "Cuba", "CUP", "+53")
INSERT INTO countries VALUES (43, "Cyprus", "CYP", "+357")
INSERT INTO countries VALUES (44, "Czech Republic", "CZK", "+420")
INSERT INTO countries VALUES (45, "Denmark", "DKK", "+45")
INSERT INTO countries VALUES (46, "Djibouti", "DJF", "+253")
INSERT INTO countries VALUES (47, "Dominica", "XCD", "+1-767")
INSERT INTO countries VALUES (48, "Dominican Republic", "DOP", "+1-809")
INSERT INTO countries VALUES (49, "Ecuador", "USD", "+593")
INSERT INTO countries VALUES (50, "Egypt", "EGP", "+20")
INSERT INTO countries VALUES (51, "El Salvador", "USD", "+503")
INSERT INTO countries VALUES (52, "Equatorial Guinea", "XAF", "+240")
INSERT INTO countries VALUES (53, "Eritrea", "ERN", "+291")
INSERT INTO countries VALUES (54, "Estonia", "EEK", "+372")
INSERT INTO countries VALUES (55, "Ethiopia", "ETB", "+251")
INSERT INTO countries VALUES (56, "Fiji", "FJD", "+679")
INSERT INTO countries VALUES (57, "Finland", "EUR", "+358")
INSERT INTO countries VALUES (58, "France", "EUR", "+33")
INSERT INTO countries VALUES (59, "Gabon", "XAF", "+241")
INSERT INTO countries VALUES (60, "Gambia", "GMD", "+220")
INSERT INTO countries VALUES (61, "Georgia", "GEL", "+995")
INSERT INTO countries VALUES (62, "Germany", "EUR", "+49")
INSERT INTO countries VALUES (63, "Ghana", "GHS", "+233")
INSERT INTO countries VALUES (64, "Greece", "EUR", "+30")
INSERT INTO countries VALUES (65, "Grenada", "XCD", "+1-473")
INSERT INTO countries VALUES (66, "Guatemala", "GTQ", "+502")
INSERT INTO countries VALUES (67, "Guinea", "GNF", "+224")
INSERT INTO countries VALUES (68, "Guinea-Bissau", "XOF", "+245")
INSERT INTO countries VALUES (69, "Guyana", "GYD", "+592")
INSERT INTO countries VALUES (70, "Haiti", "HTG", "+509")
INSERT INTO countries VALUES (71, "Honduras", "HNL", "+504")
INSERT INTO countries VALUES (72, "Hong Kong", "HKD", "+852")
INSERT INTO countries VALUES (73, "Hungary", "HUF", "+36")
INSERT INTO countries VALUES (74, "Iceland", "ISK", "+354")
INSERT INTO countries VALUES (75, "India", "INR", "+91")
INSERT INTO countries VALUES (76, "Indonesia", "IDR", "+62")
INSERT INTO countries VALUES (77, "Iran", "IRR", "+98")
INSERT INTO countries VALUES (78, "Iraq", "IQD", "+964")
INSERT INTO countries VALUES (79, "Ireland", "EUR", "+353")
INSERT INTO countries VALUES (80, "Israel", "ILS", "+972")
INSERT INTO countries VALUES (81, "Italy", "EUR", "+39")
INSERT INTO countries VALUES (82, "Jamaica", "JMD", "+1-876")
INSERT INTO countries VALUES (83, "Japan", "JPY", "+81")
INSERT INTO countries VALUES (84, "Jordan", "JOD", "+962")
INSERT INTO countries VALUES (85, "Kazakhstan", "KZT", "+7")
INSERT INTO countries VALUES (86, "Kenya", "KES", "+254")
INSERT INTO countries VALUES (87, "Kiribati", "AUD", "+686")
INSERT INTO countries VALUES (88, "Korea, (North Korea)", "KPW", "+850")
INSERT INTO countries VALUES (89, "Korea, (South Korea)", "KRW", "+82")
INSERT INTO countries VALUES (90, "Kuwait", "KWD", "+965")
INSERT INTO countries VALUES (91, "Kyrgyzstan", "KGS", "+996")
INSERT INTO countries VALUES (92, "Laos", "LAK", "+856")
INSERT INTO countries VALUES (93, "Latvia", "LVL", "+371")
INSERT INTO countries VALUES (94, "Lebanon", "LBP", "+961")
INSERT INTO countries VALUES (95, "Lesotho", "LSL", "+266")
INSERT INTO countries VALUES (96, "Liberia", "LRD", "+231")
INSERT INTO countries VALUES (97, "Libya", "LYD", "+218")
INSERT INTO countries VALUES (98, "Liechtenstein", "CHF", "+423")
INSERT INTO countries VALUES (99, "Lithuania", "LTL", "+370")
INSERT INTO countries VALUES (100, "Luxembourg", "EUR", "+352")
INSERT INTO countries VALUES (101, "Macedonia", "MKD", "+389")
INSERT INTO countries VALUES (102, "Madagascar", "MGA", "+261")
INSERT INTO countries VALUES (103, "Malawi", "MWK", "+265")
INSERT INTO countries VALUES (104, "Malaysia", "MYR", "+60")
INSERT INTO countries VALUES (105, "Maldives", "MVR", "+960")
INSERT INTO countries VALUES (106, "Mali", "XOF", "+223")
INSERT INTO countries VALUES (107, "Malta", "MTL", "+356")
INSERT INTO countries VALUES (108, "Marshall Islands", "USD", "+692")
INSERT INTO countries VALUES (109, "Mauritania", "MRO", "+222")
INSERT INTO countries VALUES (110, "Mauritius", "MUR", "+230")
INSERT INTO countries VALUES (111, "Mexico", "MXN", "+52")
INSERT INTO countries VALUES (112, "Micronesia", "USD", "+691")
INSERT INTO countries VALUES (113, "Moldova", "MDL", "+373")
INSERT INTO countries VALUES (114, "Monaco", "EUR", "+377")
INSERT INTO countries VALUES (115, "Mongolia", "MNT", "+976")
INSERT INTO countries VALUES (116, "Montenegro", "EUR", "+382")
INSERT INTO countries VALUES (117, "Morocco", "MAD", "+212")
INSERT INTO countries VALUES (118, "Mozambique", "MZM", "+258")
INSERT INTO countries VALUES (119, "Myanmar (Burma)", "MMK", "+95")
INSERT INTO countries VALUES (120, "Namibia", "NAD", "+264")
INSERT INTO countries VALUES (121, "Nauru", "AUD", "+674")
INSERT INTO countries VALUES (122, "Nepal", "NPR", "+977")
INSERT INTO countries VALUES (123, "Netherlands", "EUR", "+31")
INSERT INTO countries VALUES (124, "New Zealand", "NZD", "+64")
INSERT INTO countries VALUES (125, "Nicaragua", "NIO", "+505")
INSERT INTO countries VALUES (126, "Niger", "XOF", "+227")
INSERT INTO countries VALUES (127, "Nigeria", "NGN", "+234")
INSERT INTO countries VALUES (128, "Norway", "NOK", "+47")
INSERT INTO countries VALUES (129, "Oman", "OMR", "+968")
INSERT INTO countries VALUES (130, "Pakistan", "PKR", "+92")
INSERT INTO countries VALUES (131, "Palau", "USD", "+680")
INSERT INTO countries VALUES (132, "Palestinian", "ILS", "+970")
INSERT INTO countries VALUES (133, "Panama", "PAB", "+507")
INSERT INTO countries VALUES (134, "Papua New Guinea", "PGK", "+675")
INSERT INTO countries VALUES (135, "Paraguay", "PYG", "+595")
INSERT INTO countries VALUES (136, "Peru", "PEN", "+51")
INSERT INTO countries VALUES (137, "Philippines", "PHP", "+63")
INSERT INTO countries VALUES (138, "Poland", "PLN", "+48")
INSERT INTO countries VALUES (139, "Portugal", "EUR", "+351")
INSERT INTO countries VALUES (140, "Qatar", "QAR", "+974")
INSERT INTO countries VALUES (141, "Romania", "RON", "+40")
INSERT INTO countries VALUES (142, "Russia", "RUB", "+7")
INSERT INTO countries VALUES (143, "Rwanda", "RWF", "+250")
INSERT INTO countries VALUES (144, "Samoa", "WST", "+685")
INSERT INTO countries VALUES (145, "Saudi Arabia", "SAR", "+966")
INSERT INTO countries VALUES (146, "Senegal", "XOF", "+221")
INSERT INTO countries VALUES (147, "Serbia", "RSD", "+381")
INSERT INTO countries VALUES (148, "Seychelles", "SCR", "+248")
INSERT INTO countries VALUES (149, "Sierra Leone", "SLL", "+232")
INSERT INTO countries VALUES (150, "Singapore", "SGD", "+65")
INSERT INTO countries VALUES (151, "Slovakia", "SKK", "+421")
INSERT INTO countries VALUES (152, "Slovenia", "EUR", "+386")
INSERT INTO countries VALUES (153, "Solomon Islands", "SBD", "+677")
INSERT INTO countries VALUES (154, "Somalia", "SOS", "+252")
INSERT INTO countries VALUES (155, "South Africa", "ZAR", "+27")
INSERT INTO countries VALUES (156, "Spain", "EUR", "+34")
INSERT INTO countries VALUES (157, "Sri Lanka", "LKR", "+94")
INSERT INTO countries VALUES (158, "Sudan", "SDG", "+249")
INSERT INTO countries VALUES (159, "Suriname", "SRD", "+597")
INSERT INTO countries VALUES (160, "Swaziland", "SZL", "+268")
INSERT INTO countries VALUES (161, "Sweden", "SEK", "+46")
INSERT INTO countries VALUES (162, "Switzerland", "CHF", "+41")
INSERT INTO countries VALUES (163, "Syria", "SYP", "+963")
INSERT INTO countries VALUES (164, "Taiwan", "TWD", "+886")
INSERT INTO countries VALUES (165, "Tajikistan", "TJS", "+992")
INSERT INTO countries VALUES (166, "Tanzania", "TZS", "+255")
INSERT INTO countries VALUES (167, "Thailand", "THB", "+66")
INSERT INTO countries VALUES (168, "Timor-Leste (East Timor)", "USD", "+670")
INSERT INTO countries VALUES (169, "Togo", "XOF", "+228")
INSERT INTO countries VALUES (170, "Tonga", "TOP", "+676")
INSERT INTO countries VALUES (171, "Trinidad and Tobago", "TTD", "+1-868")
INSERT INTO countries VALUES (172, "Tunisia", "TND", "+216")
INSERT INTO countries VALUES (173, "Turkey", "TRY", "+90")
INSERT INTO countries VALUES (174, "Turkmenistan", "TMM", "+993")
INSERT INTO countries VALUES (175, "Tuvalu", "AUD", "+688")
INSERT INTO countries VALUES (176, "Uganda", "UGX", "+256")
INSERT INTO countries VALUES (177, "Ukraine", "UAH", "+380")
INSERT INTO countries VALUES (178, "United Arab Emirates", "AED", "+971")
INSERT INTO countries VALUES (179, "United Kingdom", "GBP", "+44")
INSERT INTO countries VALUES (180, "United States", "USD", "+1")
INSERT INTO countries VALUES (181, "Uruguay", "UYU", "+598")
INSERT INTO countries VALUES (182, "Uzbekistan", "UZS", "+998")
INSERT INTO countries VALUES (183, "Vanuatu", "VUV", "+678")
INSERT INTO countries VALUES (184, "Vatican City", "EUR", "+379")
INSERT INTO countries VALUES (185, "Venezuela", "VEB", "+58")
INSERT INTO countries VALUES (186, "Vietnam", "VND", "+84")
INSERT INTO countries VALUES (187, "Yemen", "YER", "+967")
INSERT INTO countries VALUES (188, "Zambia", "ZMK", "+260")
INSERT INTO countries VALUES (189, "Zimbabwe", "ZWD", "+263")
